name: Deploy AVD Landing Zone

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      LOCATION: "westeurope"
      PARAMS_FILE: "./arm-templates/parameters.json"
      RG_AVD: "HC-AVD-RG01"
      RG_VNET: "HC-AVDVNET-RG01"
      RG_IMG: "HC-AVDIMG-RG01"
      RG_STORAGE: "HC-AVDSTORAGE-RG01"
      RG_MONITOR: "HC-AVDMON-RG01"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Azure using GitHub Secret
        uses: azure/login@v1
        with:
          creds: ${{ secrets.LANDINGZONE }}

      - name: Create Resource Groups
        run: |
          echo "Creating Resource Groups..."
          az group create --name $RG_AVD --location $LOCATION || exit 1
          az group create --name $RG_VNET --location $LOCATION || exit 1
          az group create --name $RG_IMG --location $LOCATION || exit 1
          az group create --name $RG_STORAGE --location $LOCATION || exit 1
          az group create --name $RG_MONITOR --location $LOCATION || exit 1

      - name: Deploy Landing Zone Resources
        run: |
          echo "Deploying Landing Zone Resources..."
          az deployment group create \
            --resource-group $RG_VNET \
            --template-file ./arm-templates/landingzone.json \
            --parameters @$PARAMS_FILE || exit 1

      - name: Confirm Deployment
        run: |
          echo "AVD Landing Zone deployment complete!"
